ruby/testewebapp/config/routes.rb
Rails.application.routes.draw do
  
  #rotas do usuario.
  resources :users
  
  #rotas da sessão
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  #rota principal
  root 'sessions#new'

end 

ruby/testewebapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/testewebapp/app/models/user.rb
class User < ActiveRecord::Base 
    #valida a presença
    validates_presence_of :email, message: 'não pode ser deixado em branco'
    validates_presence_of :password, message: 'não pode ser deixado em branco'
    #valida o tamanho
    validates_length_of :email, minimum: 10, message: 'deve ter pelo menos 10 caracteres'
    validates_length_of :email, maximum: 260, message: 'deve ter até 260 caracteres'
    validates_length_of :password, minimum: 6, message: 'deve ter pelo menos 6 caracteres'
    
    validates_uniqueness_of :email, message: 'deve ser único'
    
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email,   format: { with: VALID_EMAIL_FORMAT, message: 'com formato invalido!'}, 
                        uniqueness: {case_sensitive: false, message: 'deve ser unico.'}
    before_save { self.email = email.downcase }
    has_secure_password
    
    validates :name,    presence: {message: 'não pode ser deixado em branco'}, 
                        length: {maximum: 50, message: 'deve ter até 50 caracteres'}

end


    #validates_presence_of :nome, message: 'não pode ser deixado em branco'
    #validates_presence_of :email, message: 'não pode ser deixado em branco'
    #validates_presence_of :telefone, message: 'não pode ser deixado em branco'
   
    #validates_length_of :nome, minimum: 2, message: 'deve ter pelo menos 3 caracteres'
    #validates_length_of :email, minimum: 10, message: 'deve ter pelo menos 10 caracteres'
    #validates_length_of :telefone, maximum: 11, message: 'deve ter até 11 caracteres'
    #validates_length_of :endereco, in: 10..100, message: 'deve ter entre 10 e 100 caracteres'
   

ruby/testewebapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    include SessionsHelper
end

ruby/testewebapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create  
    @user = User.find_by(email: params[:session][:email].downcase)
      if @user && @user.authenticate(params[:session][:password])
        sign_in(@user)
        redirect_to current_user
      else
        render action: :new
      end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

ruby/testewebapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Usuário foi criado com sucesso!"
      #tire o método de comentário quando criar o helper.
      #Usuário depois de cadastrar-se acessa o sistema automaticamente
      sign_in(@user)
    else 
      render action: :new
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

ruby/testewebapp/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/testewebapp/app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in
        session[:user_id] = @user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
        if current_user.present?
        redirect_to users_path
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end 

ruby/testewebapp/app/helpers/users_helper.rb
module UsersHelper
end

ruby/testewebapp/app/views/layouts/_header.html.erb
<header>
    <div>
        <nav>
            <ul>
                <% if logged_in? %>
                    <li><%= link_to "Users", users_path %>
                    </li>
                    <li>
                        <ul>
                            <li><%= link_to "Profile", current_user %>
                            </li>
                            <li><%= link_to "Settings", '#' %>
                            </li>
                            <li>
                                <%= link_to "Log out", sign_out_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", root_path %>
                    </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

ruby/testewebapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testewebapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

ruby/testewebapp/app/views/users/index.html.erb
<h1> Users </h1>
    <table>
        <thead>
            <tr>
                <th>Nome
                </th>
                <th>Email
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= link_to "Show", user %></td>
            </tr>
            <%end%>
        </tbody>
</table>

ruby/testewebapp/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
      <div class="alert-error">
         O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
      </div>
      <ul>
         <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
  </ul>
  </div>
<% end %>
  <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
  </div>
  <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
  </div>
  <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
      <%= f.submit "Cadastrar"%>
  </div>
<% end %>

ruby/testewebapp/app/views/users/show.html.erb
<html>
    <body>
        <h3>Perfil de <%= @user.name %> </h3>
        <%= @user.email %>
    </body>
</html>